### ISSUE TITLE
Will Not Install Under new GRAV Beta Admin

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-editor-buttons#8]
FYI ... The plugin will not install under the new GRAV Beta Admin. THX!

**Comment by flaviocopes** [comment]
Hi, cannot recreate. What's the problem? Is there any error showing up?

**Comment by oneleft** [comment]
I have the same issue.  When adding plugin it says additional dependencies need to be installed 'grav'.  Once installed,  no additional buttons are present.

**Comment by rhukster** [comment]
Are you guys both Running Grav 1.1b2?

**Comment by oneleft** [comment]
I am running 1.1b2

**Comment by rhukster** [comment]
I'm testing with the current develop branch and it installs just fine.  I think something has been fixed since b2.  This version will be released as b3 tomorrow or the next day.

```
> bin/gpm install editor-buttons

GPM Releases Configuration: Stable


Should Grav use the symlinks if available? [y|N] n

The following dependencies can be updated as there is a newer version, but it's not mandatory...
  |- Package admin
  |- Package form
  |- Package login

Update these packages? [y|N] n
Dependencies are OK

Preparing to install Editor Buttons [v1.0.0]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!


Clearing cache

Cleared:  /Users/rhuk/workspace/grav-demo-sampler/cache/compiled/*

Touched: /Users/rhuk/workspace/grav-demo-sampler/user/config/system.yaml
```

**Comment by oneleft** [comment]
Yes it installs fine, but the editor buttons do not show up.  I am now on 1.1b3 and the issue persists.

**Comment by rhukster** [comment]
Ah ok, we'll check these out!  Thanks.

**Comment by flaviocopes** [comment]
Needed a release for the testing channel. Just made it, should appear soon.

**Comment by oneleft** [comment]
very nice... test release is working fine

**Comment by ghost** [comment]
Working fine under Beta4 too. THX!
